# Generated by Django 4.0.3 on 2024-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'お知らせ', 'verbose_name_plural': 'お知らせ'},
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='満了日時'),
        ),
        migrations.AlterField(
            model_name='question',
            name='issued_date',
            field=models.DateTimeField(verbose_name='発信日時'),
        ),
        migrations.AlterField(
            model_name='question',
            name='public_method',
            field=models.CharField(choices=[('time', '時刻公開'), ('immediate', 'すぐ公開'), ('hold', '保留')],
                                   default='time', max_length=20, verbose_name='公開方式'),
        ),
        migrations.AlterField(
            model_name='question',
            name='push',
            field=models.CharField(choices=[('push-on', '通知する'), ('push-off', '通知しない')], default='push-on',
                                   max_length=20, verbose_name='プッシュ通知有無'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
